- name: RHEL 9 host survey via AAP
  hosts: all 
  gather_facts: no
  become: yes

  vars:
    survey_path: /usr/local/sbin/rhel9_host_survey.sh

  tasks:
    - name: Install survey script
      ansible.builtin.copy:
        src: files/rhel9_host_survey.sh
        dest: "{{ survey_path }}"
        mode: "0755"

    - name: Run survey
      ansible.builtin.shell: "{{ survey_path }}"
      args:
        executable: /bin/bash
      register: survey_run
      changed_when: false

    - name: Show script output (contains OUTPUT_DIR=...)
      ansible.builtin.debug:
        var: survey_run.stdout_lines

    - name: Extract output directory path
      ansible.builtin.set_fact:
        survey_outdir: "{{ (survey_run.stdout | regex_search('OUTPUT_DIR=(.*)', '\\1')) | first }}"

    - name: Ensure local destination base exists
      ansible.builtin.file:
        path: "./survey_artifacts_rhel9/{{ inventory_hostname }}"
        state: directory
        mode: "0755"
      delegate_to: localhost

    - name: Get a controller-side timestamp for filename
      ansible.builtin.set_fact:
        ts: "{{ lookup('pipe', 'date +%s') }}"
      delegate_to: localhost

    - name: Create tarball of survey output on remote (no extra collections)
      ansible.builtin.shell: |
        tar -C {{ survey_outdir | quote }} -czf /var/tmp/{{ inventory_hostname }}_survey_{{ ts }}.tar.gz .
      args:
        executable: /bin/bash
      register: survey_tar_create
      changed_when: true

    - name: Set tarball path fact
      ansible.builtin.set_fact:
        survey_tar_path: "/var/tmp/{{ inventory_hostname }}_survey_{{ ts }}.tar.gz"

    - name: Ensure /var/tmp exists on ansible.ansiblelab.com
      ansible.builtin.file:
        path: "/var/tmp"
        state: directory
        mode: "1777"
      delegate_to: ansible.ansiblelab.com

    - name: Fetch tarball to controller
      ansible.builtin.fetch:
        src: "{{ survey_tar_path }}"
        dest: "./survey_artifacts_rhel9/{{ inventory_hostname }}/"
        flat: yes

    - name: Copy tarball from controller to ansible.ansiblelab.com
      ansible.builtin.copy:
        src: "./survey_artifacts_rhel9/{{ inventory_hostname }}/{{ survey_tar_path | basename }}"
        dest: "/var/tmp/{{ inventory_hostname }}_survey_{{ ts }}.tar.gz"
        mode: "0644"
      delegate_to: ansible.ansiblelab.com

    - name: Clean up remote tarball (optional)
      ansible.builtin.file:
        path: "{{ survey_tar_path }}"
        state: absent

    - name: Clean up local tarball (optional)
      ansible.builtin.file:
        path: "./survey_artifacts_rhel9/{{ inventory_hostname }}/{{ survey_tar_path | basename }}"
        state: absent
