- name: Ensure local destination base exists
  ansible.builtin.file:
    path: "./survey_artifacts_rhel9/{{ inventory_hostname }}"
    state: directory
    mode: "0755"
  delegate_to: localhost

- name: Create tarball of survey output on remote
  ansible.builtin.archive:
    path: "{{ survey_outdir }}/"
    dest: "/var/tmp/{{ inventory_hostname }}_survey_{{
      ansible_date_time.epoch }}.tar.gz"
    format: gz
  register: survey_tar

- name: Fetch tarball to controller
  ansible.builtin.fetch:
    src: "{{ survey_tar.dest }}"
    dest: "./survey_artifacts_rhel9/{{ inventory_hostname }}/"
    flat: yes

- name: Unpack tarball locally (optional)
  ansible.builtin.unarchive:
    src: "./survey_artifacts_rhel9/{{ inventory_hostname }}/{{ survey_tar.dest | basename }}"
    dest: "./survey_artifacts_rhel9/{{ inventory_hostname }}/"
    remote_src: false
  delegate_to: localhost

- name: Clean up remote tarball (optional)
  ansible.builtin.file:
    path: "{{ survey_tar.dest }}"
    state: absent

- name: Clean up local tarball (optional)
  ansible.builtin.file:
    path: "./survey_artifacts_rhel9/{{ inventory_hostname }}/{{ survey_tar.dest | basename }}"
    state: absent
